import "./globals.css";
import Provider from "@/components/ui/theme-provider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import ConvexClientProvider from "./ConvexClientProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexClientProvider>
          <Provider>{children}</Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
